services:
  frontend:
    container_name: assistant_photo_frontend_ui
    image: maliciamrg/assistant_photo_frontend:latest
    ports:
      - "8192:3000"
    networks:
      - assistant-photo

networks:
  assistant-photo:
