version: '3.8'
services:
  frontend:
    container_name: assistant_photo_frontend_ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8192:5173"
    networks:
      - assistant-photo-front

networks:
  assistant-photo-front:
