name: assistant-photo
services:
  frontend:
    container_name: assistant_photo_frontend_ui
    image: maliciamrg/assistant_photo_frontend:latest
    environment:
      # Where your built files live in the container
      ASSET_DIR: /app/dist/assets
      # Prefix used for placeholder detection
      APP_PREFIX: PREFIX_
      # Real values for your frontend to consume
      PREFIX_API_URL: "http://192.212.10.200:8099/api"
    ports:
      - "8192:3000"
    networks:
      - assistant-photo

networks:
  assistant-photo:
